# Builds a dockerimage and then runs tests from within the docker enviroment

name: CI with docker build
on:
  push:
    branches:
    - develop
    - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test with debian Docker
        run: |
          docker build -t cubit_debian_docker -f debian.Dockerfile .
          docker run --rm cubit_debian_docker /bin/bash -c "python stp_to_h5m_cubit_script.py"

      - name: Build and test with ubuntu Docker
        run: |
          docker build -t cubit_ubuntu_docker -f ubuntu.Dockerfile .
          docker run --rm cubit_ubuntu_docker /bin/bash -c "python stp_to_h5m_cubit_script.py"
